<div id="hero" class="slide">
      <div class="text" data-0="opacity:1;transform:scale(1.0)" data-top-bottom="opacity:0.2;transform:scale(0.8)">
        <h1><img src="images/logo.png" alt="AgileSite-3" /></h1>        
        <h2>The Agile Development Tool<br/>for Oracle WebCenterSites</h2>        
        <div class="video"><iframe width="460" height="259" src="https://www.youtube.com/embed/cus7WYHdQic" frameborder="0" allowfullscreen></iframe></div>
      </div>
      <img src="images/blackswan.jpg" class="rocket" data-0="transform: perspective(10px) translate3d(0%, 0%, 0px);" data-top-center="transform: perspective(10px) translate3d(0.8%, -20%, -5.75px);" />
    </div>